# -*- coding: utf-8 -*-
"""next word predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2Fp6qty1AbgkGYPbIYOqMs0-w88T5BS
"""

faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.Intelligentai.in/courses/Intelligentai-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.Intelligentai@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.Intelligentai.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.Intelligentai@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.Intelligentai@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

#next step encoding
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical

import numpy as np

tokens=Tokenizer()

tokens.fit_on_texts([faqs])

tokens.word_index

input_sequences=[]
for s in faqs.split("\n"):
  Tokenize_sequences=tokens.texts_to_sequences([s])[0]
  for i in range(1,len(Tokenize_sequences)):
    n_gram_sequence=Tokenize_sequences[:i+1]
    input_sequences.append(n_gram_sequence)

input_sequences

max_len=max([len(x) for x in input_sequences])
max_len

from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_sequences=pad_sequences(input_sequences,maxlen=max_len,padding="pre")

padded_sequences

x=padded_sequences[:,:-1]
y=padded_sequences[:,-1]

#train and fit
from tensorflow.keras.utils import to_categorical

y=to_categorical(y,num_classes=len(tokens.word_index)+1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

model=Sequential()
model.add(Embedding(input_dim=len(tokens.word_index)+1,output_dim=100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(len(tokens.word_index)+1,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

#model fit
model.fit(x,y,epochs=100)

#summary
model.summary()

#now predict first word
text="what is the fee"
token_text=tokens.texts_to_sequences([text])[0]
padded_tokens=pad_sequences([token_text],maxlen=max_len-1,padding="pre")
padded_sequences=model.predict(padded_sequences)
ps=np.argmax(padded_sequences)
for word,index in tokens.word_index.items():
  if index==ps:
    text=text+" "+word
    print(text)

from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# Let's say you have this input
text = "what is the fee"

# Convert text to token sequence
token_list = tokens.texts_to_sequences([text])[0]

# Pad it to match the model's input length
padded = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

# Predict the probabilities for the next word
predicted_probs = model.predict(padded, verbose=0)

# Get the index of the word with highest probability
predicted_index = np.argmax(predicted_probs)

# Map index back to word
for word, index in tokens.word_index.items():
    if index == predicted_index:
        predicted_word = word
        break

# Add predicted word to input
new_text = text + " " + predicted_word
print("Predicted Text:", new_text)

text = "what is the fee"

for _ in range(5):  # generate 5 more words
    token_list = tokens.texts_to_sequences([text])[0]
    padded = pad_sequences([token_list], maxlen=max_len-1, padding='pre')
    predicted_probs = model.predict(padded, verbose=0)
    predicted_index = np.argmax(predicted_probs)

    # Map index back to word
    for word, index in tokens.word_index.items():
        if index == predicted_index:
            text += " " + word
            break

print("Generated Sentence:", text)

from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

text = "what is the fee"  # starting seed text
max_generated_words = 30  # safety cap to avoid infinite loop

for _ in range(max_generated_words):
    # Step 1: Convert text to sequence
    token_list = tokens.texts_to_sequences([text])[0]

    # Step 2: Pad the sequence
    padded = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

    # Step 3: Predict next word
    predicted_probs = model.predict(padded, verbose=0)
    predicted_index = np.argmax(predicted_probs)

    # Step 4: Map index back to word
    predicted_word = None
    for word, index in tokens.word_index.items():
        if index == predicted_index:
            predicted_word = word
            break

    # Step 5: Stop if word is not found or if it hits special token
    if predicted_word is None or predicted_word in ['end', 'stop', 'pad']:
        break

    # Step 6: Add predicted word to text
    text += ' ' + predicted_word

print("\n📜 Final Generated Sentence:\n", text)